/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EcTech {
        "angular": string;
        "animation": string;
        "article": string;
        "cdk": string;
        "cli": string;
        "components": string;
        "i18n": string;
        "material": string;
        "node": string;
        "npm": string;
        "pwa": string;
        "repo": string;
        "universal": string;
    }
}
declare global {
    interface HTMLEcTechElement extends Components.EcTech, HTMLStencilElement {
    }
    var HTMLEcTechElement: {
        prototype: HTMLEcTechElement;
        new (): HTMLEcTechElement;
    };
    interface HTMLElementTagNameMap {
        "ec-tech": HTMLEcTechElement;
    }
}
declare namespace LocalJSX {
    interface EcTech {
        "angular"?: string;
        "animation"?: string;
        "article"?: string;
        "cdk"?: string;
        "cli"?: string;
        "components"?: string;
        "i18n"?: string;
        "material"?: string;
        "node"?: string;
        "npm"?: string;
        "pwa"?: string;
        "repo"?: string;
        "universal"?: string;
    }
    interface IntrinsicElements {
        "ec-tech": EcTech;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ec-tech": LocalJSX.EcTech & JSXBase.HTMLAttributes<HTMLEcTechElement>;
        }
    }
}
